<?php
header("HTTP/1.1 404 Not Found");
$_BODY['title'] = __('Error 404');
$_BODY['page'] = '404';
$_BODY['robots'] = false;
load_template('header')
?>
<div class="container">
	<img src="<?php load_img('p404.png') ?>">
	<h3>
		<?php _e('We could not find that!') ?>
	</h3>
	<form method="GET" action="<?php echo url() . 'search/' ?>">
		<div class="input-field">
			<input type="text" name="q">
			 <label class="active">
			 	<i class="fa fa-search"></i>
			 	&nbsp;<?php _e('Search') ?>
			 </label>
		</div>
	</form>
	<ul>
		<li>
			<a href="javascript:history.back();">
				<?php _e('Back') ?>
			</a>
		</li>
		<li>
			<a href="<?php echo url() ?>">
				<?php _e('Home') ?>
			</a>
		</li>
		<?php if( ! is_logged() ): ?>
		<li>
			<a href="<?php echo url() . 'signin.php' ?>">
				<?php _e('Sign In') ?>
			</a>
		</li>
		<?php endif ?>
	</ul>
</div>
<?php load_template('footer');