<?php
$a = $_BODY['audio'];
$u = $_BODY['user'];
$can_listen = can_listen($u->id);
if( ! $can_listen )
	return load_full_template('404'); // u cannot get here
$t = $u->user . ': ';
if( strlen($a->description) > 10 )
	$t .= substr($a->description, 0, 10) . '...';
else
	$t .= $a->description;
$_BODY['title'] = $t;
$_BODY['robots'] = (bool) $u->audios_public;
load_template('header')
?>
<div class="content" id="main">
	<div class="row">
		<div class="col l9 m12 s12">
			<div class="box">
				<?php display_audio($a, true) ?>
				<hr>
				<p class="title">
					<?php _e('Replies') ?>
				</p>
				<div id="replies">
			<?php load_replies($a->id) ?>
				</div>
		<?php if( is_logged() ): ?>
				<form method="POST"
				id="form_reply"
				action="<?php
				echo url() . INC . 'ajax/reply.php'
				?>">
				<input type="hidden" name="id" value="<?php echo $a->id ?>">
					<div class="input-field">
   						<textarea class="materialize-textarea" name="reply" maxlength="200" id="reply_box" maxlength="200"></textarea>
						<label>
						<i class="fa fa-pencil"></i>
					<?php _e('Write a reply') ?>
						</label>
					</div>
					<div id="reply_options">
						<input type="hidden" name="s_twitter" value="0">
						<input type="checkbox" id="twsent" name="s_twitter" >
						<label for="twsent">
					<?php _e('Send to Twitter') ?>
						</label>
						<button type="submit" class="btn right waves-effect waves-light">
					<?php _e('Reply') ?>
						<i class="fa fa-send"></i>
						</button>
					</div>
				</form>
		<?php else: ?>
			<a
			class="signin"
			href="<?php echo url() . 'signin.php' ?>"
			>
				<img src="<?php load_img('signin.png') ?>">
			</a>
		<?php endif ?>
			</div>
		</div>
		<div class="col l3 m12 s12">
			<?php load_template('sidebar') ?>
		</div>
	</div>
</div>
<script type="text/javascript">
var is_audio = true,
audio_id = '<?php echo $a->id ?>';
</script>
<?php load_template('footer');