<?php
$a = $_BODY['audio'];
$u = $_BODY['user'];
$can_listen = can_listen($u->id);
if( ! $can_listen )
	return load_full_template('404'); // u cannot get here
$t = $u->user . ': ';
if( strlen($a->description) > 10 )
	$t .= substr($a->description, 0, 10) . '...';
else
	$t .= $a->description;
$_BODY['title'] = $t;
$_BODY['robots'] = (bool) $u->audios_public;
load_template('header')
?>
<div class="content" id="main">
	<div class="row">
		<div class="col l9 m12 s12">
			<div class="box">
				<?php display_audio($a, true) ?>
				<div class="share_buttons">
					<script type="text/javascript" async src="https://platform.twitter.com/widgets.js"></script>
					<a
					class="twitter-share-button"
					data-size="large"
					href="https://twitter.com/intent/tweet?<?php
echo http_build_query( array(
			'text' => sprintf(
					__("Listen to @%s's audio"),
					$u->user
					),
			'via' => 'twit_audio',
			'related' => 'twit_audio,zerquix18,superjd10_,chusen'
			)
		)
					?>">
					<i class="fa fa-twitter"></i>&nbsp;
						Tweet
					</a>
				</div>
				<hr>
				<p class="title">
					<?php _e('Replies') ?>
				</p>
				<div id="replies">
			<?php load_replies($a->id) ?>
				</div>
		<?php if( is_logged() ): ?>
				<form method="POST"
				id="form_reply"
				action="<?php
				echo url() . INC . 'ajax/reply.php'
				?>">
				<input type="hidden" name="id" value="<?php echo $a->id ?>">
					<div class="input-field">
   						<textarea class="materialize-textarea" name="reply" maxlength="200" id="reply_box" maxlength="200"></textarea>
						<label>
						<i class="fa fa-pencil"></i>
					&nbsp;<?php _e('Write a reply') ?>
						</label>
					</div>
					<div id="reply_options">
						<input type="hidden" name="s_twitter" value="0">
						<input checked="checked" type="checkbox" id="twsent" name="s_twitter" value="1">
						<label for="twsent">
					<?php _e('Send to Twitter') ?>
						</label>
						<button type="submit" class="btn right waves-effect waves-light">
					<?php _e('Reply') ?>&nbsp;
						<i class="fa fa-send"></i>
						</button>
					</div>
				</form>
		<?php else: ?>
			<a
			class="signin"
			href="<?php
			echo url() . 'signin.php?back_to=' .
			urlencode( url() . $_SERVER['REQUEST_URI'] )
			?>"
			>
				<img src="<?php load_img('signin.png') ?>">
			</a>
		<?php endif ?>
			</div>
		</div>
		<div class="col l3 m12 s12">
			<?php load_template('sidebar') ?>
		</div>
	</div>
</div>
<script type="text/javascript">
var is_audio = true,
audio_id = '<?php echo $a->id ?>';
linked = "<?php if( defined('LINKED') ) echo constant('LINKED') ?>";
</script>
<?php load_template('footer');