<?php
$_BODY['page'] = 'default';
load_template('header')
?>
<div class="content" id="main">
	<div class="row">
		<div class="col l9 m12 s12">
			<div id="norecordsupport" class="red-text" style="display:none;">
	<?php echo sprintf( __('Your current browser does not support audio recording. See which <a href="%s">browsers support audio recording</a>.'), url() . 'faq#q1')
	?>
			</div>
			<?php load_template('post') ?>
			<div class="row">
				<div class="col l6 m12 s12">
					<div class="box">
						<p class="title">
					<?php _e('Your recent audios') ?>
						</p>
			<?php
			$audios = $db->query(
					'SELECT * FROM audios
					WHERE reply_to = \'0\'
					AND user = ?
					ORDER BY `time` DESC
					LIMIT 3',
					$_USER->id
				);
			if( $audios->nums == 0 ):
				alert_info( __("Here we'll show you your most recent audios. Why not starting with an audio about you signing?") );
			else:
				while( $a = $audios->r->fetch_object() )
					display_audio( $a );
			endif;
			?>
					</div>
				</div>
				<div class="col l6 m12 s12">
					<div class="box">
						<p class="title">
				<?php _e('Popular audios right now') ?>
						</p>
			<?php
$recents = $db->query(
			'SELECT * FROM audios
			WHERE user NOT IN (
					SELECT id
					FROM users
					WHERE audios_public = \'0\'
					)
			AND reply_to = \'0\'
			AND `time` BETWEEN ? AND ?
			ORDER BY plays DESC
			LIMIT 3',
			time() - strtotime('-30 days'),
			time()
	);
	if( $recents->nums === 0 ):
		alert_info( __("We'll show you here the most recent popular audios when available!") );
	else:
		while( $r = $recents->r->fetch_object() )
			display_audio($r);
	endif;
			?>
					</div>
				</div>
			</div>
		</div>
		<div class="col l3 m12 s12">
			<?php load_template('sidebar') ?>
		</div>
	</div>
</div>
<?php
load_template('footer');