<?php load_template('header') ?>
	<div class="container h">
		<div class="row">
			<div id="le_content" class="column">
			<?php if( isset($_SESSION['first_time']) ): ?>
				<div id="firstime" class="prompt">
				<div class="welcome_text">
					<?php _e('Welcome to TwitAudio!'); ?>
				</div><hr>
				<?php
				echo __('Everything was set up. ');
				if( ! (int) $_USER->audios_public ) 
					echo sprintf( __('Your audios and favorites were set and private because your Twitter account is protected. You can change this in your <a href="%s">settings</a>.'), url() . 'settings' ) . ' ';
				echo '<br>' . __('We hope you enjoy TwitAudio. <3') . ' ';
				?>
				<a href="javascript:void(0)" id="close_ft"><i class="fa fa-times-circle"></i>&nbsp;<?php _e('Close') ?></a>
				</div>
			<?php unset($_SESSION['first_time']); endif ?>
				<div id="norecordsupport" class="prompt" style="display:none;">
					<?php echo sprintf( __('Your current browser does not support audio recording. Read <a href="%s">here</a> how to solve it.'), url() . 'faq#q1');
					?>
				</div>
			<?php load_template('post') ?>
				<div class="box down">
					<p class="title"><?php _e('Your recent audios') ?></p>
					<?php
					$audios = $db->query("SELECT * FROM audios WHERE user = ? AND reply_to = '0' ORDER BY time DESC LIMIT 3", $_USER->id);
					if( $audios->nums == 0 ):
						alert_error( __("You haven't recorded or uploaded audios... yet. "), true );
					else:
						while($a = $audios->r->fetch_object() )
							display_audio($a);
						?>
						<?php
					endif;
					?>
					<ul class="sn">
						<li class="left">
							<a href="<?php echo url() . 'settings' ?>">&larr;
								<?php _e('Go to settings') ?>
							</a>
						</li>
						<?php if($audios->nums > 0): ?>
						<li class="right">
							<a href="<?php echo url() . 'audios/' . $_USER->user ?>">
								<?php _e('See all your audios') ?>
							&rarr;</a>
						</li>
						<?php endif ?>
					</ul>
				</div>
			</div>
			<?php load_template('sidebar') ?>
		</div>
	</div>
	<?php load_template('footer') ?>
</body>
</html>