<?php $a = $_BODY['audio'] ?>
<!DOCTYPE html>
<html>
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="<?php echo $_BODY['css_url'] . 'default.css' ?>">
	<link rel="stylesheet" href="<?php echo $_BODY['css_url'] ?>font-awesome.css">
	<link rel="apple-touch-icon" href="<?php echo $_BODY['img_url'] ?>apple-icon.png">
	<link rel="icon" href="<?php echo $_BODY['img_url'] ?>favicon.ico">
	<script src="<?php echo $_BODY['js_url'] ?>jquery-1.11.3.min.js"></script>
	<style type="text/css">
	body{background:none;}
	</style>
</head>
<body>
<script>
//<![CDATA[
$(document).ready( function() {

    $("#player_<?php echo $a->id ?>").jPlayer({
        ready: function(event) {
            $(this).jPlayer("setMedia", {
				mp3: "<?php echo url() . INC . 'audios/' . $a->audio ?>",
            });
        },
        cssSelectorAncestor : '#container_<?php echo $a->id ?>',
        swfPath: "http://jplayer.org/latest/dist/jplayer",
        supplied: "mp3",
		wmode: "window",
		useStateClassSkin: true,
		autoBlur: false,
		smoothPlayBar: true,
		keyEnabled: true,
		remainingDuration: true,
		toggleDuration: true
    });
});
//]]>
</script>
<div id="player_<?php echo $a->id ?>" class="jp-jplayer"></div>
    <div id="container_<?php echo $a->id ?>" class="jp-audio sm">
        <div class="jp-type-single">
            <div class="jp-gui jp-interface">
                <ul class="jp-controls">
                    <li><a href="javascript:;" class="jp-play plei" data-id="<?php echo $a->id ?>" tabindex="1"><i class="fa fa-play control"></i></a></li>
                    <li><a href="javascript:;" class="jp-pause" tabindex="1"><i class="fa fa-pause control"></i></a></li>
                    <li><a href="javascript:;" class="jp-stop" tabindex="1">stop</a></li>
                    <li><a href="javascript:;" class="jp-mute" tabindex="1" title="mute"><i class="fa fa-volume-up vcontrol"></i></a></li>
                    <li><a href="javascript:;" class="jp-unmute" tabindex="1" title="unmute"><i class="fa fa-volume-down vcontrol"></i></a></li>
                    <li><a href="javascript:;" class="jp-volume-max" tabindex="1" title="max volume">max volume</a></li>
                </ul>
                <div class="jp-progress">
                    <div class="jp-seek-bar">
                        <div class="jp-play-bar"></div>
                    </div>
                </div>
                <div class="jp-volume-bar">
                    <div class="jp-volume-bar-value"></div>
                </div>
                <div class="jp-current-time"></div>
                <div class="jp-duration"></div>
            </div>
            <div class="jp-no-solution">
                <?php _e('<span>Update Required</span>
                To play the media you will need to either update your browser to a recent version or update your <a href="http://get.adobe.com/flashplayer/" target="_blank">Flash plugin</a>') ?>.
            </div>
        </div>
    </div>
    <script>
    ajaxurl = '<?php echo url() . INC . "ajax/" ?>';
    </script>
   <script src="<?php echo $_BODY['js_url'] ?>jquery.jplayer.min.js"></script>
    <script src="<?php echo $_BODY['js_url'] . 'default.js' ?>"></script>
    </body>
    </html>