<?php
$u = $_BODY['user'];
$is_fav = isset($_GET['l']);
$are_favs_visible = 
(int) $u->favs_public || ( is_logged() && $u->id == $_USER->id );
$are_audios_visible = can_listen($u->id);
$_BODY['title'] = $is_fav ?
	sprintf( __("%s favorites"), $u->user )
:
	$u->user;
$audios_count = $db->query(
		'SELECT COUNT(*) AS size FROM audios
		WHERE reply_to = \'0\' AND user = ?',
		$u->id
	);
$audios_count = (int) $audios_count->size;
$favs_count = $db->query(
		'SELECT COUNT(*) AS size FROM favorites WHERE user_id = ?',
		$u->id
	);
$favs_count = (int) $favs_count->size;
load_template('header');
?>
<div class="content" id="main">
	<div class="row">
		<div class="col l9 m12 s12">
			<div class="box">
				<img
				src="<?php echo get_image($u->avatar) ?>"
				class="circle z-depth-3 materialboxed"
				id="propic"
				data-caption="<?php
				echo sprintf(
					__("%s's profile picture"),
					$u->user
				)
				?>">
				<h5 id="name">
					<?php
					echo htmlspecialchars($u->name);
					verified($u->verified)
					?>
				</h5>
				<p id="user" class="grey-text lighten-2-text">
					@<?php echo $u->user ?>
				</p>
				<div id="bio">
			<?php echo htmlspecialchars($u->bio) ?>
				</div>
				<ul class="tabs" id="pnavigation">
					<li class="tab">
						<a class="blue-text <?php
					if( ! $is_fav ) echo 'active' ?>"
						href="<?php
			echo url() . 'audios/' . $u->user
						?>">
						<?php _e('Audios') ?>&nbsp;
		<?php if( $audios_count && $are_audios_visible  ): ?>
							<span class="bdge blue lighten-2">
				<?php echo format_number($audios_count) ?>
							</span>
		<?php endif ?>
						</a>
					</li>
					<li class="tab">
						<a class="blue-text <?php
					if( $is_fav ) echo 'active' ?>"
						href="<?php
			echo url() . 'favorites/' . $u->user
						?>">
						<?php _e('Favorites') ?>&nbsp;
			<?php if( $favs_count && $are_favs_visible ): ?>
							<span class="bdge yellow darken-2">
				<?php echo format_number($favs_count) ?>
							</span>
			<?php endif ?>
						</a>
					</li>
				</ul>
				<div id="<?php
				if( $is_fav )
					echo 'favorites';
				else
					echo 'audios'
				?>">
		<?php
		$call = $is_fav ? 'load_favs' : 'load_audios';
		if( $is_fav ? $are_favs_visible : $are_audios_visible ):
			$call($u->id);
		else: // no much talking, you just cannot see em'!
			if( $is_fav )
				alert_error(
					__("This user's favorites are private.")
				);
			else
				alert_error(
					__("This user's audios are private.")
				);
		endif;
		?>
				</div>
			</div>
		</div>
		<div class="col l3 m12 s12">
			<?php load_template('sidebar') ?>
		</div>
	</div>
</div>
<script type="text/javascript">
var profile = '<?php echo $u->user ?>';
</script>
<?php load_template('footer');