<?php
$_BODY['page'] = 'search';
$_BODY['q'] =
$query = validate_args(@$_GET['q']) ? trim($_GET['q']) : '';
$_BODY['title'] =
	htmlspecialchars($query, ENT_QUOTES, 'utf-8') . ' ' . __('Search');

load_template('header');
/**
* d = date
* p = page
**/
$sort = validate_args( @$_GET['s'] )
	&& in_array($_GET['s'], array("d", "p") ) ?
		$_GET['s']
	:
		'd';
/**
* u = users
* a = audios
**/
$type = validate_args( @$_GET['t'] )
	&& in_array($_GET['t'], array('u', 'a') ) ?
		$_GET['t']
	:
		'a';
?>
<div class="content" id="main">
	<div class="row">
		<div class="col l9 m12 s12">
			<div class="box">
				<form method="GET" action="<?php echo url() . 'search' ?>">
				<div class="input-field">
					<input type="text" class="validate" name="q" id="s">
					<label for="s">
						<i class="fa fa-search"></i>
						&nbsp;<?php _e('Search...') ?>
					</label>
				</div>
				<div id="search_options">
				<div class="input-field col s3 left">
				<select id="search_type" name="t">
					<option value="a"
					<?php if( 'a' == $type )
					echo 'selected="selected"'
					?>><?php _e('Audios') ?></option>
					<option value="u"
					<?php if( 'u' == $type )
					echo 'selected="selected"'
					?>><?php _e('Users') ?></option>
				</select>
				<label><?php _e('Type') ?></label>
				</div>
				<div class="input-field col s3 right">
				<select id="search_sort" name="s"
				<?php
				if( 'u' == $type )
					echo 'disabled="disabled"';
				?>>
					<option value="d"
					<?php if( 'd' == $sort )
					echo 'selected="selected"'
					?>><?php _e('Date') ?></option>
					<option value="p"
					<?php if( 'p' == $sort )
					echo 'selected="selected"'
					?>><?php _e('Plays') ?></option>
				</select>
				<label><?php _e('Sort') ?></label>
				</div>
  				</div>
  				<button id="search_button" type="submit" class="waves-effect waves-light btn blue lighten-1">
  					<?php _e('Search') ?>
  				</button>
  				</form>
  				<div class="divider search"></div>
  				<p class="title"><?php _e('Results') ?></p>
  				<div id="search">
  				<?php
  				if( ! empty($query) )
  					search(
  						$query,
  						$sort,
  						$type,
  						$page = 1
  					)
  				?>
  				</div>
  			</div>
		</div>
		<div class="col l3 m12 s12">
			<?php load_template('sidebar') ?>
		</div>
	</div>
</div>
<?php if( ! empty($q) ): ?>
<script type="text/javascript">
window.onload = function() {
	$("#q, #s").val( decodeURIComponent("<?php echo urlencode($_GET['q']) ?>") );
	$("#q, #s").addClass('valid');
	$("label[for='s'], label[for='q']").addClass('active');
};
var search = "<?php echo urlencode($_GET['q']) ?>";
var type = "<?php echo $type ?>";
var sort = "<?php echo $sort ?>";
</script>
<?php
endif; load_template('footer');