<form method="POST" id="settings_form" method="POST" action="<?php echo url() . 'assets/ajax/settings.php' ?>">
	<p class="title"><?php _e('Privacy') ?></p>
	<input type="hidden" name="audios_public" value="0">
	<input type="checkbox"
	name="audios_public"
	class="filled-in"
	id="settings_audio"
<?php if( (int) $_USER->audios_public ): ?>
	checked="checked"
<?php endif ?>
	value="1">
	<label for="settings_audio">
		<?php _e('Make my audios public') ?>
	</label>
	<br>
	<input type="hidden" name="favs_public" value="0">
	<input type="checkbox"
	name="favs_public"
	class="filled-in"
	id="settings_favorites"
<?php if( (int) $_USER->favs_public ): ?>
	checked="checked"
<?php endif ?>
	value="1">
	<label for="settings_favorites">
		<?php _e('Make my favorites public') ?>
	</label>
	<p><?php _e('If your audios are private, only your followers will be able to see/listen to them. On the other hand, if your favorites are private, only you will be able to see them.') ?>
	</p>
	<hr>
	<button type="submit" class="btn waves-effect waves-light">
		<?php _e('Update settings') ?>&nbsp;
		<i class="fa fa-send"></i>
	</button>
</form>