<?php
$_BODY['page'] = 'txt';
$replace = array(
		'about' 		=> __('About'),
		'tos' 		=> __('Terms of Service'),
		'privacy' 	=> __('Privacy Policy'),
		'faq' 		=> 'FAQ',
		'contact' 	=>__('Contact')
	);
$_BODY['title'] = str_replace(
		array_keys($replace),
		array_values($replace),
		$_GET['txt']
	);
load_template('header')
?>
<div class="container">
	<div id="alltxt">
		<?php echo file_get_contents(
			$_SERVER['DOCUMENT_ROOT']
				. '/html/' . $_GET['txt'] . '.html'
			) ?>
	</div>
</div>
<?php load_template('footer');