<?php
$_BODY['page'] = 'txt';
$rplc = array(
		'about' 		=> __('About'),
		'tos' 		=> __('Terms of Service'),
		'privacy' 	=> __('Privacy Policy'),
		'faq' 		=> 'FAQ',
		'contact' 	=>__('Contact')
	);
$_BODY['title'] = str_replace(
		array_keys($rplc),
		array_values($rplc),
		$_GET['txt']
	);
load_template('header')
?>
<div class="container">
	<div id="alltxt">
		<?php echo file_get_contents( PATH . INC . 'html/' . $_GET['txt'] . '.html' ) ?>
	</div>
</div>
<?php load_template('footer');