<?php
/**
* Template file for the
* administration's footer
* @author Zerquix18 <zerquix18@hotmail.com>
* @copyright Copyright (c) 2016 Luis A. Martínez
*
**/
?>
</div>
<script type="text/javascrpt" src="<?php load_script('jquery-1.11.3.min.js') ?>">
</script>
<script type="text/javascrpt" src="<?php load_script('materialize.js') ?>">
</script>
<script type="text/javascrpt" src="<?php load_script('default.js') ?>">
</script>
</body>
</html>