<?php
/**
* Template file for the
* administration's header
* @author Zerquix18 <zerquix18@hotmail.com>
* @copyright Copyright (c) 2016 Luis A. Martínez
*
**/
?>
<!DOCTYPE html>
<html>
<head>
	<title>TwitAudio's root</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="robots" content="noindex,nofollow">
	<link rel="stylesheet" href="<?php load_style('materialize.css') ?>">
	<link rel="stylesheet" href="<?php load_style('default.css') ?>">
	<link rel="stylesheet" href="<?php adm_load_style('default.css') ?>">
	<link rel="stylesheet" href="<?php load_style('font-awesome.css') ?>">
	<link rel="icon" href="<?php load_img('favicon.ico') ?>">
	<script src="<?php load_script('jquery-1.11.3.min.js') ?>"></script>
	<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/morris.js/0.5.1/morris.css">
	<script src="//cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
	<script src="//cdnjs.cloudflare.com/ajax/libs/morris.js/0.5.1/morris.min.js"></script>
</head>
<body>
<div id="slide-out" class="side-nav fixed  grey darken-3">
	<form method="GET" action="<?php echo url() . 'search' ?>">
		<div class="input-field">
			<input
				type="text"
				class="validate"
				id="q"
				name="q"
				title="<?php
				_e('Type something to search')
				?>"
				>
			<label for="q">
				<i class="fa fa-search"></i>
				&nbsp;Search...
			</label>
		</div>
	</form>
	<ul id="userthings">
		<li>
			<a
			title="Go to the homepage"
			href="<?php echo url() ?>">
				<i class="fa fa-home"></i>
				Homepage
			</a>
		</li>
		<li <?php if( adm_is('dashboard') ): ?>
			class="active grey darken-2"
			<?php endif ?>
		>
			<a
			title="Go to the dashboard"
			href="<?php echo url() . 'root/' ?>">
				<i class="fa fa-dashboard"></i>
				Dashboard
			</a>
		</li>
		<li <?php if( adm_is('audios') ): ?>
			class="active grey darken-2"
			<?php endif ?>
		>
			<a
			title="Audio's page"
			href="<?php echo url() . 'root/audios.php' ?>">
				<i class="fa fa-headphones"></i>
				Audios
			</a>
		</li>
		<li <?php if( adm_is('replies') ): ?>
			class="active grey darken-2"
			<?php endif ?>
		>
			<a
			title="Audio's page"
			href="<?php echo url() . 'root/replies.php' ?>">
				<i class="fa fa-reply"></i>
				Replies
			</a>
		</li>
		<li <?php if( adm_is('users') ): ?>
			class="active grey darken-2"
			<?php endif ?>
		>
			<a
			title="User's page"
			href="<?php echo url() . 'root/users.php' ?>">
				<i class="fa fa-user"></i>
				Users&nbsp;
			</a>
		</li>
		<li>
			<a
			title="Bye bye"
			href="<?php echo url() . '?logout=1' ?>">
				<i class="fa fa-sign-out"></i>
				Logout&nbsp;
			</a>
		</li>
	</ul>
</div>
<div class="navbar-fixed">
	<nav class="blue lighten-2 content">
		<a href="javascript:void(0);" data-activates="slide-out" class="button-collapse" id="open_sidebar"><i class="mdi-navigation-menu"></i></a>
		<div class="nav-wrapper">
			<a href="<?php echo url() ?>" class="brand-logo center logo">TwitAudio #</a>
		</div>
	</nav>
</div>
<div class="content" id="admin">