<?php
use \application\View;
header("HTTP/1.1 404 Not Found");
View::set_page('404');
View::load_template('header', array(
		'title'	 => 'Error 404',
		'robots' => false
	)
)
?>
<div class="container">
	<img src="<?php View::load_img('p404.png') ?>">
	<h3 class="not-found-text">
		<?php _e('We could not find that!') ?>
	</h3>
	<form method="GET" action="<?php echo url() . 'search/' ?>">
		<div class="input-field">
			<input
				type="text"
				name="q"
				title="<?php _e('Type something to search') ?>"
				>
			 <label class="active">
			 	<i class="fa fa-search"></i>
			 	&nbsp;<?php _e('Search') ?>
			 </label>
		</div>
	</form>
	<ul>
		<li>
			<a href="javascript:history.back();">
				<?php _e('Back') ?>
			</a>
		</li>
		<li>
			<a href="<?php echo url() ?>">
				<?php _e('Home') ?>
			</a>
		</li>
		<?php if( ! is_logged() ): ?>
		<li>
			<a href="<?php echo url() . 'signin' ?>">
				<?php _e('Sign In') ?>
			</a>
		</li>
		<?php endif ?>
	</ul>
</div>
<?php View::load_template('footer');