<?php
/**
* Template for audio pages
* The variable $template comes
* from the AudioController
*
**/
use \application\Views;
Views::set_page('audio');

$audio   = $template['audio'];
$user  	 = $audio->user;
$replies = $template['replies'];
$linked  = $template['linked'];

$title = $user->user . ': ';
if( strlen($audio->description) > 10 )
	$title .= substr($audio->description, 0, 10) . '...';
else
	$title .= $audio->description;
Views::load_template('header', array(
		'title'		=> $title,
		'robots'	=> (bool) $user->audios_public
	)
);
?>
<div class="content" id="main">
	<div class="row">
		<div class="col l9 m12 s12">
			<div class="box">
				<?php
				Views::display_audio($audio, array('size' => 'big') )
				?>
				<div class="share_buttons">
					<script type="text/javascript" async src="https://platform.twitter.com/widgets.js"></script>
					<a
					class="twitter-share-button"
					data-size="large"
					href="https://twitter.com/intent/tweet?<?php
echo http_build_query( array(
			'text' => sprintf(
					__("Listen to @%s's audio"),
					$user->user
					),
			'via' => 'twit_audio',
			'related' => 'twit_audio,zerquix18,superjd10_,chusen'
			)
		)
					?>">
					<i class="fa fa-twitter"></i>&nbsp;
						Tweet
					</a>
				</div>
				<hr>
				<p class="title">
					<?php _e('Replies') ?>
				</p>
		<?php if( is_logged() ): ?>
				<form method="POST"
				id="form_reply"
				action="<?php
				echo url() . 'ajax/post/reply'
				?>">
				<input type="hidden" name="id" value="<?php echo $audio->id ?>">
					<div class="input-field">
   						<textarea class="materialize-textarea" name="reply" maxlength="200" id="reply_box" maxlength="200" required="required"></textarea>
						<label id="label_reply">
						<i class="fa fa-pencil"></i>
					&nbsp;<?php _e('Write a reply') ?>
						</label>
					</div>
					<div id="reply_options">
						<input type="hidden" name="s_twitter" value="0">
						<input checked="checked" type="checkbox" id="twsent" name="s_twitter" value="1">
						<label for="twsent">
					<?php _e('Send to Twitter') ?>
						</label>
						<button type="submit" class="btn right waves-effect waves-light">
					<?php _e('Reply') ?>&nbsp;
						<i class="fa fa-send"></i>
						</button>
					</div>
				</form>
		<?php else: ?>
			<a
			class="signin"
			title="<?php _e('You must be logged in to leave a reply') ?>"
			href="<?php
			echo url() . 'signin?back_to=' .
			urlencode( url() . substr($_SERVER['REQUEST_URI'], 1) )
			?>"
			>
				<img src="<?php Views::load_img('signin.png') ?>">
			</a>
		<?php endif ?>
			<div class="divider"></div>
				<div id="replies">
			<?php
				if( empty($replies) )
					Views::alert_info(
						__("There are not replies yet... Be the first!")
					);
				else {
					while( list(,$reply) = each($replies['audios']) )
						Views::display_audio( $reply );
					if( $replies['load_more'] )
						Views::load_more('replies', 2);
				}
			?>
				</div>
			</div>
		</div>
		<div class="col l3 m12 s12">
			<?php Views::load_template('sidebar') ?>
		</div>
	</div>
</div>
<script type="text/javascript">
var audio_id = '<?php echo $audio->id ?>',
linked = "<?php if( ! empty($linked) ) echo $linked ?>";
</script>
<?php Views::load_template('footer');