<?php
use \application\Views;
$recent_audios  = $template['recent_audios'];
$recent_popular = $template['recent_popular'];
Views::set_page('default');
Views::load_template('header');
?>
<?php if( ! isset($_COOKIE['noscript']) && ! isset($_GET['_ta_script']) ): ?>
<noscript>
	<meta http-equiv="refresh" content="0; URL=/?_ta_noscript=1">
</noscript>
<?php endif ?>
<div class="content main">
	<div class="row">
		<div class="col l9 m12 s12">
			<div id="norecordsupport" class="red-text" style="display:none;">
	<?php echo sprintf( __('Your current browser does not support audio recording. See which <a href="%s">browsers support audio recording</a>.'), url('faq#q1') )
	?>
			</div>
			<?php if( isset($_GET['_ta_noscript']) && ! isset($_COOKIE['noscript']) ) {
				setcookie('noscript', '1', time()+3600);
				// a user without js wont last too much
				?>
			<div class="red-text">
		<?php
		_e('Your current browser does not support Javascript or is disactivated for this page. Some features may not work without Javascript.');
		?>
			</div>
				<?php
			}
			?>
			<?php Views::load_template('post') ?>
			<div class="row">
				<div class="col l6 m12 s12">
					<div class="box">
						<p class="title">
					<?php _e('Your recent audios') ?>
						</p>
			<?php
			if( count($recent_audios) == 0 ):
				Views::alert_info( __("Here we'll show you your most recent audios. Why not starting with an audio about you signing?") );
			else:
				while( list(,$audio) = each($recent_audios) )
					Views::display_audio( $audio );
			endif;
			?>
					</div>
				</div>
				<div class="col l6 m12 s12">
					<div class="box">
						<p class="title">
				<?php _e('Popular audios right now') ?>
						</p>
			<?php
	if( count($recent_popular) ):
		Views::alert_info( __("We'll show you here the most recent popular audios when available!") );
	else:
		while( list(,$audio) = each($recent_popular) )
			Views::display_audio($audio);
	endif;
			?>
					</div>
				</div>
			</div>
		</div>
		<div class="col l3 m12 s12">
			<?php Views::load_template('sidebar') ?>
		</div>
	</div>
</div>
<?php
Views::load_template('footer');