<?php
/**
*
* The template file for frame
* $template comes from the FrameController
* A really dirty file
*
**/
use \application\View;
$audio = $template['audio']
?>
<!DOCTYPE html>
<html>
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1">
    <?php
    $all_styles = file_get_contents(
            $_SERVER['DOCUMENT_ROOT'] . '/assets/css/styles.json'
        );
    $all_styles = json_decode( $all_styles, true );
    if( '0' === $GLOBALS['_CONFIG']['minify_html'] ) {
        // if not live
        foreach( $all_styles as $dir => $styles ):
            $styles_count = count($styles);
            for($i = 0; $i < $styles_count; $i++):
        ?>
                <link
                rel="stylesheet"
                href="<?php
                View::load_style(
                        'load_style.php?style=' . $dir . '/' . $styles[$i]
                    )
                ?>"
                >
        <?php
            endfor;
        endforeach;
    }else{
        // live!
        foreach( $all_styles as $dir => $all_styles ): ?>
        <link
        rel="stylesheet"
        href="<?php View::load_style( $dir . '.css' ) ?>"
        >
        <?php 
        endforeach;
    }
    ?>
	<link rel="apple-touch-icon" href="<?php View::load_img('apple-icon.png') ?>">
	<link rel="icon" href="<?php View::load_img('favicon.ico') ?>">
	<style type="text/css">
	body{background:none;height:auto;}
	</style>
    <script type="text/javascript">
        window.onLoadFunctions = [];
    </script>
</head>
<body>
<script>
//<![CDATA[
window.onLoadFunctions.push( function() {

    $("#player_<?php echo $audio->id ?>").jPlayer({
        ready: function(event) {
            $(this).jPlayer("setMedia", {
				mp3: "<?php echo $audio->audio ?>",
            });
        },
        cssSelectorAncestor : '#container_<?php echo $audio->id ?>',
        swfPath: "http://jplayer.org/latest/dist/jplayer",
        supplied: "mp3",
		wmode: "window",
		useStateClassSkin: true,
		autoBlur: false,
		smoothPlayBar: true,
		keyEnabled: true,
		remainingDuration: true,
		toggleDuration: true
    });
});
//]]>
</script>
<div id="player_<?php echo $audio->id ?>" class="jp-jplayer"></div>
    <div id="container_<?php echo $audio->id ?>" class="jp-audio sm">
        <div class="jp-type-single">
            <div class="jp-gui jp-interface">
                <ul class="jp-controls">
                    <li><a href="javascript:;" class="jp-play plei" data-id="<?php echo $audio->id ?>" tabindex="1"><i class="fa fa-play control"></i></a></li>
                    <li><a href="javascript:;" class="jp-pause" tabindex="1"><i class="fa fa-pause control"></i></a></li>
                    <li><a href="javascript:;" class="jp-stop" tabindex="1"></a></li>
                    <li><a href="javascript:;" class="jp-mute" tabindex="1" title="mute"><i class="fa fa-volume-up vcontrol"></i></a></li>
                    <li><a href="javascript:;" class="jp-unmute" tabindex="1" title="unmute"><i class="fa fa-volume-down vcontrol"></i></a></li>
                    <li><a href="javascript:;" class="jp-volume-max" tabindex="1" title="max volume"></a></li>
                </ul>
                <div class="jp-progress">
                    <div class="jp-seek-bar">
                        <div class="jp-play-bar"></div>
                    </div>
                </div>
                <div class="jp-volume-bar">
                    <div class="jp-volume-bar-value"></div>
                </div>
                <div class="jp-current-time"></div>
                <div class="jp-duration"></div>
            </div>
            <div class="jp-no-solution">
                <span>Update Required</span>
                To play the media you will need to either update your browser to a recent version or update your <a href="http://get.adobe.com/flashplayer/" target="_blank">Flash plugin</a>.
            </div>
        </div>
    </div>
    <script>
    ajaxUrl = '<?php echo url() . "ajax/" ?>';
    </script>
    <?php
    $all_scripts = file_get_contents(
            $_SERVER['DOCUMENT_ROOT'] . '/assets/js/scripts.json'
        );
    $all_scripts = json_decode( $all_scripts, true );
    if( '0' === $GLOBALS['_CONFIG']['minify_html'] ) {
        // if not live
        foreach( $all_scripts as $dir => $scripts ):
            $scripts_length = count($scripts);
            for($i = 0; $i < $scripts_length; $i++):
        ?>
                <script
                type="text/javascript"
                src="<?php View::load_script( $dir . '/' . $scripts[$i] ) ?>"
                ></script>
        <?php
            endfor;
        endforeach;
    }else{
        // live!
        foreach( $all_scripts as $dir => $scripts ): ?>
        <script
        type="text/javascript"
        src="<?php View::load_script( $dir . '.js' ) ?>"
        ></script>
        <?php 
        endforeach;
    }
    ?>
    </body>
    </html>