<?php
/**
*
* The template file for frame
* $template comes from the FrameController
* A really dirty file
*
**/
use \application\Views;
$audio = $template['audio']
?>
<!DOCTYPE html>
<html>
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="<?php Views::load_style('default.css') ?>">
	<link rel="stylesheet" href="<?php Views::load_style('font-awesome.css') ?>">
	<link rel="apple-touch-icon" href="<?php Views::load_img('apple-icon.png') ?>">
	<link rel="icon" href="<?php Views::load_img('favicon.ico') ?>">
	<script src="<?php Views::load_script('jquery-1.11.3.min.js') ?>"></script>
	<style type="text/css">
	body{background:none;height:auto;}
	</style>
</head>
<body>
<script>
//<![CDATA[
$(document).ready( function() {

    $("#player_<?php echo $audio->id ?>").jPlayer({
        ready: function(event) {
            $(this).jPlayer("setMedia", {
				mp3: "<?php echo $audio->audio ?>",
            });
        },
        cssSelectorAncestor : '#container_<?php echo $audio->id ?>',
        swfPath: "http://jplayer.org/latest/dist/jplayer",
        supplied: "mp3",
		wmode: "window",
		useStateClassSkin: true,
		autoBlur: false,
		smoothPlayBar: true,
		keyEnabled: true,
		remainingDuration: true,
		toggleDuration: true
    });
});
//]]>
</script>
<div id="player_<?php echo $audio->id ?>" class="jp-jplayer"></div>
    <div id="container_<?php echo $audio->id ?>" class="jp-audio sm">
        <div class="jp-type-single">
            <div class="jp-gui jp-interface">
                <ul class="jp-controls">
                    <li><a href="javascript:;" class="jp-play plei" data-id="<?php echo $audio->id ?>" tabindex="1"><i class="fa fa-play control"></i></a></li>
                    <li><a href="javascript:;" class="jp-pause" tabindex="1"><i class="fa fa-pause control"></i></a></li>
                    <li><a href="javascript:;" class="jp-stop" tabindex="1"></a></li>
                    <li><a href="javascript:;" class="jp-mute" tabindex="1" title="mute"><i class="fa fa-volume-up vcontrol"></i></a></li>
                    <li><a href="javascript:;" class="jp-unmute" tabindex="1" title="unmute"><i class="fa fa-volume-down vcontrol"></i></a></li>
                    <li><a href="javascript:;" class="jp-volume-max" tabindex="1" title="max volume"></a></li>
                </ul>
                <div class="jp-progress">
                    <div class="jp-seek-bar">
                        <div class="jp-play-bar"></div>
                    </div>
                </div>
                <div class="jp-volume-bar">
                    <div class="jp-volume-bar-value"></div>
                </div>
                <div class="jp-current-time"></div>
                <div class="jp-duration"></div>
            </div>
            <div class="jp-no-solution">
                <?php _e('<span>Update Required</span>
                To play the media you will need to either update your browser to a recent version or update your <a href="http://get.adobe.com/flashplayer/" target="_blank">Flash plugin</a>') ?>.
            </div>
        </div>
    </div>
    <script>
    ajaxurl = '<?php echo url() . "assets/ajax/" ?>';
    </script>
   <script src="<?php Views::load_script('jquery.jplayer.min.js') ?>"></script>
    <script src="<?php Views::load_script('default.js') ?>"></script>
    </body>
    </html>