<?php
use \application\View;
View::set_page('index');
View::load_template('header')
?>
<div class="home-header">
	<div class="container home-logo">
		<img class="logo-full" src="<?php View::load_img('logo-full.png') ?>">
		<h2 class="home-slogan">
			Share voice notes and audios using Twitter
		</h2>
		<a href="<?php echo url('signin') ?>">
			<img class="signin" src="<?php View::load_img('signin.png') ?>">
		</a>
	</div>
</div>
<div class="container white home-features">
	<div class="row">
		<div class="col s12 m4 l4">
			<p class="center-align"><i class="fa fa-microphone fa-5x"></i></p>
			<p class="center-align">Record</p>
			<p>
					Sing, scream, talk, or just transmit what's around you. You can record up to 2 minutes and share unlimited audios.
			</p>
		</div>
		<div class="col s12 m4 l4">
			<p class="center-align"><i class="fa fa-upload fa-5x"></i></p>
			<p class="center-align">
				Upload
			</p>
			<p>
				Don't want to record your voice? <br>Upload an audio from your computer!
			</p>
		</div>
		<div class="col s12 m4 l4">
			<p class="center-align"><i class="fa fa-twitter fa-5x"></i></p>
			<p class="center-align">
				Share to Twitter
			</p>
			<p>
				After an audio is uploaded, you can share it directly to Twitter and play them through the Twitter website.
			</p>
		</div>
	</div>
	<div class="row">
		<div class="col s12 m4 l4 offset-m2 offset-l2">
			<p class="center-align"><i class="fa fa-star fa-5x"></i></p>
			<p class="center-align">
				Favorite everything
			</p>
			<p>
				You can favorite audios to save them for later, say you like them,
				or even just to make people know you listened to them.
			</p>
		</div>
		<div class="col s12 m4 l4">
			<p class="center-align"><i class="fa fa-magic fa-5x"></i></p>
			<p class="center-align">
				Add Effects
			</p>
			<p>
				Make your audios even more awesome!
			</p>
		</div>
	</div>
</div>
<?php View::load_template('footer');