<?php
use \application\Views;
Views::set_page('index');
Views::load_template('header')
?>
<div id="home">
	<div class="container" id="logo">
		<img class="logo-full" src="<?php Views::load_img('logo-full.png') ?>">
		<h2>
		<?php _e('Share voice notes and audio files using Twitter') ?>
		</h2>
		<a href="<?php echo url('signin') ?>">
			<img src="<?php Views::load_img('signin.png') ?>">
		</a>
	</div>
</div>
<div class="container white" id="features">
	<div class="row">
		<div class="col s12 m4 l4">
			<p class="center-align"><i class="fa fa-microphone fa-5x"></i></p>
			<p class="center-align"><?php _e('Record') ?></p>
			<p>
				<?php _e("Sing, scream, talk, or just transmit what's around you. You can record up to 2 minutes unlimited audios and share them.") ?>
			</p>
		</div>
		<div class="col s12 m4 l4">
			<p class="center-align"><i class="fa fa-upload fa-5x"></i></p>
			<p class="center-align">
				<?php _e('Upload') ?>
			</p>
			<p>
				<?php _e("Don't want to share your voice? Upload the song that you're listening. Sure your followers will love it.") ?>
			</p>
		</div>
		<div class="col s12 m4 l4">
			<p class="center-align"><i class="fa fa-twitter fa-5x"></i></p>
			<p class="center-align">
				<?php _e('Share to Twitter') ?>
			</p>
			<p>
				<?php _e("After an audio is uploaded, you can share it directly to Twitter and play them through the Twitter website.") ?>
			</p>
		</div>
	</div>
	<div class="row">
		<div class="col s12 m4 l4 offset-m2 offset-l2">
			<p class="center-align"><i class="fa fa-star fa-5x"></i></p>
			<p class="center-align">
				<?php _e('Favorite everything') ?>
			</p>
			<p>
				<?php _e("You can favorite audios to save them for later, say you like them, or even just to make people know you listened to them.") ?>
			</p>
		</div>
		<div class="col s12 m4 l4">
			<p class="center-align"><i class="fa fa-comment fa-5x"></i></p>
			<p class="center-align">
				<?php _e('Express yourself') ?>
			</p>
			<p>
				<?php _e("Reply to other's people audios. and interact with them.") ?>
			</p>
		</div>
	</div>
</div>
<?php Views::load_template('footer');