<?php
$current_user = (new \models\User())->get_current_user();
if( $current_user->is_premium() ): ?>
ur premium m8!
<?php else: ?>

<div class="row">
    <div class="col s12">
    	<ul class="tabs">
			<li class="tab col s3">
        		<a href="#premium_overview">
        			Overview
        		</a>
        	</li>
        	<li class="tab col s3">
        		<a class="active" href="#premium_get">
        			Get premium
        		</a>
        	</li>
			<li class="tab col s3 disabled">
				<a href="#premium_enjoy">
					Enjoy!
				</a>
			</li>
		</ul>
	</div>
    <div id="premium_overview" class="col s12">
    	Test 1
    </div>
    <div id="premium_get" class="col s12">
        <form id="form-premium">
        <div class="form-premium-inputs">
			<div class="row">
				<div class="input-field col s12">
					<i class="material-icons prefix">credit_card</i>
					<input data-stripe="number" type="text" class="validate">
					<label for="icon_prefix">Card Number</label>
				</div>
          </div>
			<div class="row">
				<div class="input-field col s6">
					<i class="material-icons prefix">view_agenda</i>
					<input data-stripe="exp" type="text" class="validate">
					<label for="icon_prefix">Exp. date (MM/YY)</label>
				</div>
				<div class="input-field col s6">
					<i class="material-icons prefix">lock_outline</i>
					<input data-stripe="cvc" type="text" class="validate">
					<label for="icon_prefix">CVC</label>
				</div>
          </div>
        </div>
        <button
		id="submit-premium"
		type="submit"
		class="btn waves-effect waves-light center">
			Make me premium!&nbsp;
			<i class="fa fa-send"></i>
		</button>
        </form>
    </div>
    <div id="premium_enjoy" class="col s12">
    	Test 4
    </div>
</div>
        
<?php endif ?>