<?php
use \models\Users;
$current_user  = Users::get_current_user();
$is_premium    = $current_user->is_premium();
$premium_until = $current_user->premium_until;
?>
<div class="row">
    <div class="col s12">
    	<ul class="tabs premium-tabs">
			<li
			class="tab col s3"
			id="premium-overview-selector">
        		<a
        		<?php if( ! $is_premium ): ?>
        		class="blue-text active"
        		<?php else: ?>
        		class="blue-text"
        		<?php endif ?>
        		href="#premium-overview">
        			Overview
        		</a>
        	</li>
        	<li
        	<?php if( $is_premium ): ?>
			class="tab col s3 disabled"
			<?php else: ?>
			class="tab col s3"
			<?php endif ?>
        	id="premium-get-selector">
        		<a
        		<?php if( $is_premium ): ?>
        		class="blue-text text-lighten-4"
        		<?php else: ?>
        		class="blue-text"
        		<?php endif ?>
        		href="#premium-get">
        			Get premium
        		</a>
        	</li>
			<li
			<?php if( $is_premium ): ?>
			class="tab col s3"
			<?php else: ?>
			class="tab col s3 disabled"
			<?php endif ?>
			id="premium-enjoy-selector">
				<a
				<?php if( $is_premium ): ?>
					class="blue-text active"
				<?php else: ?>
					class="blue-text text-lighten-4"
				<?php endif ?>
				href="#premium-enjoy">
					Enjoy!
				</a>
			</li>
		</ul>
	</div>
    <div id="premium-overview" class="col s12">
    	<h4>Become premium!</h4>
    	<!--
    		Worst design for a premium overview
    		But I promise to change it :'v
    	-->
    	<p>Being premium brings you the following features:</p>
    	<ul class="collection">
    		<li class="collection-item">
    			<i class="fa fa-plus"></i>&nbsp;
    			5 minutes to upload your voice notes or audios
    		</li>
    		<li class="collection-item">
    			<i class="fa fa-magic"></i>&nbsp;
    			9 more effects
    		</li>
    		<li class="collection-item">
    			<i class="fa fa-thumbs-up"></i>&nbsp;
    			The quality in the audios is not decreased
    		</li>
    		<li class="collection-item">
    			<i class="fa fa-ban"></i>
    			No ads!
    		</li>
    	</ul>
    	<p>The price is <strong>1,30</strong> US dollars.</p>
    	
    </div>
    <div id="premium-get" class="col s12">
        <h5>Credit Card</h5>
        <form id="form-premium">
        <div class="form-premium-inputs">
			<div class="row">
				<div class="input-field col s12">
					<i class="material-icons prefix">credit_card</i>
					<input
					id="premium-input-card"
					data-stripe="number"
					type="text"
					class="validate">
					<label
					for="premium-input-card"
					data-success="Alright!">
						Card Number
					</label>
				</div>
          </div>
			<div class="row">
				<div class="input-field col s6">
					<i class="material-icons prefix">view_agenda</i>
					<input
					id="premium-input-exp"
					data-stripe="exp"
					type="text"
					class="validate">
					<label
					for="premium-input-exp"
					data-success="Alright!"
					>
						Exp. date (MM/YY)
					</label>
				</div>
				<div class="input-field col s6">
					<i class="material-icons prefix">lock_outline</i>
					<input
					id="premium-input-cvc"
					data-stripe="cvc"
					type="text"
					class="validate">
					<label
					for="premium-input-cvc"
					data-success="Alright!"
					>
						CVC
					</label>
				</div>
          </div>
        </div>
        <button
		id="submit-premium"
		type="submit"
		class="btn waves-effect waves-light center">
			Make me premium!&nbsp;
			<i class="fa fa-send"></i>
		</button>
        </form>
    </div>
    <div id="premium-enjoy" class="col s12">
    	<h4 class="premium-text-enjoy">Congratulations, you are premium!</h4>
    	You can enjoy all the features until
    	<span id="premium-until">
    		<?php
    			if( $is_premium ) {
    				echo date('d/m/Y', $premium_until);
    			}
    		?>
    	</span>!
    	<button
    	id="premium-button-record"
    	class="premium-button-record btn waves-effect waves-light blue lighten-3"
    	>
    		<i class="fa fa-circle"></i>&nbsp;
    		Start recording!
    	</button>
    </div>
</div>