<?php

use \application\View;
use \application\HTTP;

View::set_page('profile');
$user 	 = $template['user'];
$page 	 = $template['page'];
$errors  = $template['errors'];
$content = $template['content'];
$total_audios	 = $template['total_audios'];
$total_favorites = $template['total_favorites'];

if( 'favorites' == $page )
	$title = sprintf('%s favorites', $user['user']);
else
	$title = sprintf('%s audios', $user['user']);
View::load_template('header', array(
		'title'	=> $title
	)
);
?>
<div class="content main">
	<div class="row">
		<div class="col l9 m12 s12">
			<div class="box">
				<img
				src="<?php echo \get_avatar($user['avatar']) ?>"
				class="circle z-depth-3 materialboxed profile-picture"
				data-caption="<?php
				echo sprintf(
					"%s's profile picture",
					$user['user']
				)
				?>"
				onerror="this.src='<?php View::load_img('unknown.png') ?>'; $(this).removeClass('materialboxed')"
				>
				<h5 class="profile-name">
					<?php
					echo HTTP::xss_protect($user['name']);
					View::show_verified_badge($user['verified'])
					?>
				</h5>
				<p class="grey-text lighten-2-text profile-user">
					@<?php echo $user['user'] ?>
				</p>
				<div class="profile-bio">
			<?php echo HTTP::xss_protect($user['bio']) ?>
				</div>
				<ul class="tabs profile-navigation">
					<li class="tab">
						<a class="blue-text <?php
					if( 'audios' == $page ) echo 'active' ?>"
						href="<?php
			echo url() . 'audios/' . $user['user']
						?>">
						Audios&nbsp;
		<?php if( false !== $content && $total_audios > 0 ): ?>
							<span class="_badge blue lighten-2">
				<?php echo format_number($total_audios) ?>
							</span>
		<?php endif ?>
						</a>
					</li>
					<li class="tab">
						<a class="blue-text <?php
					if( 'favorites' == $page ) echo 'active' ?>"
						href="<?php
			echo url() . 'favorites/' . $user['user']
						?>">
						Favorites&nbsp;
			<?php if( false !== $content && $total_favorites > 0 ): ?>
							<span class="_badge yellow darken-2">
				<?php echo format_number($total_favorites) ?>
							</span>
			<?php endif ?>
						</a>
					</li>
				</ul>
				<div id="<?php
				if( 'favorites' == $page )
					echo 'favorites';
				else
					echo 'audios'
				?>">
		<?php
			if( false == $content ) {
				View::alert_error($errors['forbidden']);
			}elseif( 0 == count( $content['audios']) ) {
				View::alert_error($errors['empty']);
			}else{

				while( list(,$audio) = each($content['audios']) )
					View::display_audio( $audio );
				if( $content['load_more'] )
					View::load_more( $page, 2);

			}
		?>
				</div>
			</div>
		</div>
		<div class="col l3 m12 s12">
			<?php View::load_template('sidebar') ?>
		</div>
	</div>
</div>
<script type="text/javascript">
var profile = '<?php echo $user['user'] ?>';
</script>
<?php View::load_template('footer');