<?php
use \application\View, \application\HTTP;

View::set_page('search');

$query = $template['query'];
$type  = $template['type'];
$sort  = $template['order'];
$content = $template['content'];

$title =  HTTP::xss_protect( $query ) . ' Search';

View::load_template('header', array(
		'title'	=> $title
	)
);

?>
<div class="content main">
	<div class="row">
		<div class="col l9 m12 s12">
			<div class="box">
				<form method="GET" action="<?php echo url() . 'search' ?>">
				<div class="input-field">
					<input type="text" class="validate" name="q" id="s">
					<label for="s">
						<i class="fa fa-search"></i>
						&nbsp;Search...
					</label>
				</div>
				<div class="search_options">
				<div class="input-field col s3 left">
				<select id="search_type" name="t">
					<option value="a"
					<?php if( 'a' == $type )
					echo 'selected="selected"'
					?>>Audios</option>
					<option value="u"
					<?php if( 'u' == $type )
					echo 'selected="selected"'
					?>>Users</option>
				</select>
				<label>Type</label>
				</div>
				<div class="input-field col s3 right">
				<select id="search_sort" name="s"
				<?php
				if( 'u' == $type )
					echo 'disabled="disabled"';
				?>>
					<option value="d"
					<?php if( 'd' == $sort )
					echo 'selected="selected"'
					?>>Date</option>
					<option value="p"
					<?php if( 'p' == $sort )
					echo 'selected="selected"'
					?>>Plays</option>
				</select>
				<label>Sort</label>
				</div>
  				</div>
  				<button
  				type="submit"
  				class="search-btn waves-effect waves-light btn blue lighten-1"
  				>
  					Search
  				</button>
  				</form>
  				<div class="divider search"></div>
  				<p class="title">Results</p>
  				<div id="search">
  				<?php
  				if( ! empty($query) ):
  					/* it's looking for something! */
  					if( empty( $content['audios'] ) ):
  						?>
  					<p class="center grey-text">
  						We could not find anything.
  							Please try with a different criteria.
  					</p>
  					<?php else:
  						$function_to_call =
  							$type == 'a' ? 'display_audio' : 'display_user';
  						while( list(,$audio) = each($content['audios']) )
  							View::$function_to_call( $audio );

  						if( $content['load_more'] ):
  							View::load_more('search', 2);
  						endif;

  					endif;

  				else: ?>
  				<p class="center grey-text">
  					Type something in the search box.
  							The results will appear here.
  				</p>
  				<?php endif;
  				?>
  				</div>
  			</div>
		</div>
		<div class="col l3 m12 s12">
			<?php View::load_template('sidebar') ?>
		</div>
	</div>
</div>
<?php if( ! empty($query) ): ?>
<script type="text/javascript">
window.onload_functions.push( function() {
	$("#q, #s").val( decodeURIComponent("<?php echo urlencode($query) ?>") );
	$("#q, #s").addClass('valid');
	$("label[for='s'], label[for='q']").addClass('active');
});

var search = "<?php echo urlencode($query) ?>",
	type   = "<?php echo $type ?>",
	sort   = "<?php echo $sort ?>";
	
</script>
<?php
endif; View::load_template('footer');