<?php
use \application\View,
	\Models\Users;
	
$user = Users::get_current_user();
?>
<form
	method="POST"
	id="settings_form"
	action="<?php echo url() . 'ajax/post/settings' ?>">
	<p class="title">Privacy</p>
	<input type="hidden" name="audios_public" value="0">
	<input type="checkbox"
	name="audios_public"
	class="filled-in"
	id="settings_audio"
<?php if( (int) $user->audios_public ): ?>
	checked="checked"
<?php endif ?>
	value="1">
	<label for="settings_audio">
		Make my audios public
	</label>
	<br>
	<input type="hidden" name="favs_public" value="0">
	<input type="checkbox"
	name="favs_public"
	class="filled-in"
	id="settings_favorites"
<?php if( (int) $user->favs_public ): ?>
	checked="checked"
<?php endif ?>
	value="1">
	<label for="settings_favorites">
		Make my favorites public
	</label>
	<p>If your audios are private, only your followers will be able to see/listen to them. On the other hand, if your favorites are private, only you will be able to see them.
	</p>
	<hr>
	<button type="submit" class="btn waves-effect waves-light center">
		Update settings&nbsp;
		<i class="fa fa-send"></i>
	</button>
</form>