<?php
/**
*
* Template file for text pages
*
* @author Zerquix18 
**/

use \application\View;

View::set_page('txt');

$replace = array(
		'about' 	=> __('About'),
		'terms' 	=> __('Terms of Service'),
		'privacy' 	=> __('Privacy Policy'),
		'faq' 		=> 'FAQ',
		'contact' 	=> __('Contact'),
		'licensing' => __('Licensing'),
	);
View::load_template('header', array(
		'title' 	=> str_replace(
							array_keys($replace),
							array_values($replace),
							$template['page']
						)
	)
)
?>
<div class="container">
	<div class="text-text">
		<?php echo $template['text'] ?>
	</div>
</div>
<?php View::load_template('footer');
/* COUNTDOWN TO THE SCIENTIST! */