	<?php if( ! in_array($_BODY['page'], array("txt", "index") ) ): ?>
		<div class="ads_footer">
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-1967021427191293"
     data-ad-slot="1547888976"
     data-ad-format="auto"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
		</div>
	<?php endif ?>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-69290712-1', 'auto');
  ga('send', 'pageview');

</script>
		<footer class="container <?php if( $_BODY['page'] == 'index') echo 'home'; else echo 'center' ?>">
		<?php if( $_BODY['page'] == 'index' && count($lenguajeso) > 1 ): ?>
			<ul class="left">
			<?php foreach($lenguajeso as $a => $b ): ?>
				<li><a href="<?php echo url() . '?l=' . $a ?>"><?php echo $b ?></a></li>
			<?php endforeach ?>
			</ul>
		<?php endif ?>
			<ul<?php if($_BODY['page'] == 'index') echo ' class="right"' ?>>
				<li>
					<a href="<?php echo url() ?>about"><?php _e('About') ?>
					</a></li>
				<li>
					<a href="<?php echo url() ?>tos"><?php _e('Terms') ?>
					</a></li>
				<li>
					<a href="<?php echo url() ?>privacy">	<?php _e('Privacy') ?>
					</a></li>
				<li>
					<a href="<?php echo url() ?>faq"><?php _e('FAQ') ?>
					</a></li>
				<li>
					<a href="<?php echo url() ?>contact">	<?php _e('Contact') ?>
					</a>
				</li>
			</ul>
		</footer>
		<script>
			workerpath = "<?php echo $_BODY['js_url'] . 'recorderWorker.js' ?>";
			lamepath = "<?php echo $_BODY['js_url'] . 'lame.all.js' ?>";
			ajaxurl = '<?php echo url() . INC . "ajax/" ?>';
			swfpath = '<?php echo url() . INC . "swf/" ?>';
		</script>
		<script src="<?php echo $_BODY['js_url'] ?>ajaxform.js"></script>
		<?php if( ! in_array($_BODY['page'], array("process", "index", "settings") ) ): ?>
		<script src="<?php echo $_BODY['js_url'] ?>jquery.jplayer.min.js"></script>
		<?php endif;
		if( $_BODY['post_box'] ):
		?>
		<script src="<?php echo $_BODY['js_url'] ?>lame.all.js"></script>
		<script src="<?php echo $_BODY['js_url'] ?>recorder.js"></script>
		<?php endif;
		if( !in_array($_BODY['page'], array("index", "process") ) ): ?>
		<script src="<?php echo $_BODY['js_url'] . 'default.js' ?>"></script>
		<?php endif;