<div class="box">
	<div class="row" id="post">
		<div class="col" id="record">
			<i class="fa fa-microphone blue-text lighten-3-text"></i>
			<div class="a_text">record</div>
		</div>
		<div class="col c" id="or">or</div>
		<div class="col" id="upload">
			<i class="fa fa-upload blue-text lighten-3-text"></i>
			<div class="a_text">upload</div>
		</div>
	</div>
	<div id="waiting" class="valign-wrapper" style="display:none">
		<div class="valign" id="waiting_text">
			<i class="fa fa-refresh fa-spin"></i>&nbsp;
			Waiting for microphone access...
		</div>
	</div>
	<div id="loading" style="display:none">
		<p id="whatsloading">Uploading...</p>
		<div class="progress blue lighten-4">
			<div class="determinate blue" id="up_progress" style="width: 0%">
			</div>
		</div>
	</div>
	<div id="record_form" style="display:none">
		<div>You can record up to 2 minutes.</div>
		<span id="cleft">Recording in <span id="cleftn">3</span>...</span>
		<hr>
		<div id="record_actions">
			<i class="fa fa-stop" title="Stop" id="stop"></i>
			&nbsp;<span id="count">0:00</span>
			<span id="cancel" title="Cancel">
				<i class="fa fa-times-circle"></i>
				&nbsp;Cancel
			</span>
		</div>
	</div>
	<form method="POST"
	action="<?php echo url() . INC . 'ajax/upload.php' ?>"
	enctype="multipart/form-data"
	style="display:none;" id="up_form">
		<input type="file" id="up_file" name="up_file" style="visibility: 	hidden; display: none;" accept=".mp3,.aac,.m4a,.wav,.ogg">
	</form>
	<form method="POST"
	action="<?php echo url() . INC . 'ajax/cut.php' ?>"
	id="cut_form" style="display:none">
		<p class="center">
			I'm sorry! That audio is too long :( Would you like to cut it a bit?
		</p>
		<div id="player_cut" class="jp-jplayer"></div>
		<div id="cut_container" class="jp-audio sm audio_preview">
			<div class="jp-type-single">
  				<div class="jp-gui jp-interface">
					<ul class="jp-controls">
						<li><a href="javascript:;" class="jp-play" tabindex="1"><i class="fa fa-play control"></i></a></li>
						<li><a href="javascript:;" class="jp-pause" tabindex="1"><i class="fa fa-pause control"></i></a></li>
						<li><a href="javascript:;" class="jp-stop" tabindex="1">stop</a></li>
						<li><a href="javascript:;" class="jp-mute" tabindex="1" title="mute"><i class="fa fa-volume-up vcontrol"></i></a></li>
						<li><a href="javascript:;" class="jp-unmute" tabindex="1" title="unmute"><i class="fa fa-volume-down vcontrol"></i></a></li>
						<li><a href="javascript:;" class="jp-volume-max" tabindex="1" title="max volume">max volume</a></li>
					</ul>
					<div class="jp-progress">
						<div class="jp-seek-bar">
							<div class="jp-play-bar"></div>
						</div>
					</div>
					<div class="jp-volume-bar">
						<div class="jp-volume-bar-value"></div>
					</div>
					<div class="jp-current-time"></div>
					<div class="jp-duration"></div>
				</div>
				<div class="jp-no-solution" style="display:none">
					<span>Update Required</span>To play the media you will need to either update your browser to a recent version or update your <a href="http://get.adobe.com/flashplayer/" target="_blank">Flash plugin</a>.
				</div>
			</div>
		</div>
		<input type="hidden" name="id" id="audio_id">
		<div id="cut_block">
			Start: <input type="text" id="start" name="start" value="0:00"> | End: <input type="text" name="end" id="end" value="2:00">
		</div>
		<hr>
		<button type="submit" class="btn" id="cut_button"><i class="fa fa-scissors"></i>&nbsp;Cut</button><button type="button" id="cut_cancel" class="btn"><i class="fa fa-times-circle"></i>&nbsp;Cancel</button>
	</form>
	<form method="POST" action="<?php echo url() . INC . 'ajax/post.php' ?>" id="post_form" style="display:none">
		<p class="center">Your audio is ready!</p>
		<div id="player_preview" class="jp-jplayer"></div>
		<div id="preview_container" class="jp-audio sm audio_preview">
			<div class="jp-type-single">
  				<div class="jp-gui jp-interface">
					<ul class="jp-controls">
						<li><a href="javascript:;" class="jp-play" tabindex="1"><i class="fa fa-play control"></i></a></li>
						<li><a href="javascript:;" class="jp-pause" tabindex="1"><i class="fa fa-pause control"></i></a></li>
						<li><a href="javascript:;" class="jp-stop" tabindex="1">stop</a></li>
						<li><a href="javascript:;" class="jp-mute" tabindex="1" title="mute"><i class="fa fa-volume-up vcontrol"></i></a></li>
						<li><a href="javascript:;" class="jp-unmute" tabindex="1" title="unmute"><i class="fa fa-volume-down vcontrol"></i></a></li>
						<li><a href="javascript:;" class="jp-volume-max" tabindex="1" title="max volume">max volume</a></li>
					</ul>
					<div class="jp-progress">
						<div class="jp-seek-bar">
							<div class="jp-play-bar"></div>
						</div>
					</div>
					<div class="jp-volume-bar">
						<div class="jp-volume-bar-value"></div>
					</div>
					<div class="jp-current-time"></div>
					<div class="jp-duration"></div>
				</div>
				<div class="jp-no-solution" style="display:none">
					<span>Update Required</span>To play the media you will need to either update your browser to a recent version or update your <a href="http://get.adobe.com/flashplayer/" target="_blank">Flash plugin</a>.
				</div>
			</div>
		</div>
		<input type="hidden" name="id" id="a_id">
		<div class="input-field" id="desc_">
			<textarea maxlength="200" id="desc" name="description" class="materialize-textarea"></textarea>
			<label for="desc">
				<i class="fa fa-pencil"></i>&nbsp;Type a description
			</label>
		</div>
		<div id="send_to_twitter">
			<input type="hidden" name="s_twitter" value="0">
			<input type="checkbox" class="filled-in" id="s_twitter" checked="checked" name="s_twitter" value="1">
			<label for="s_twitter">Send to Twitter</label>
		</div>
		<hr>
		<div id="post_buttons">
			<button class="btn" type="submit">Post&nbsp;<i class="fa fa-send"></i></button> | <button type="button" id="post_cancel" class="btn">Cancel&nbsp;<i class="fa fa-times-circle"></i></button>
		</div>
	</form>
</div>