<?php
/**
* The footer template
* Included in all files
* @author Zerquix18
* @copyright Copyright (c) 2015 Luis A. Martínez
*
**/
use \application\View;

// get the info to show after login
View::load_template('login');

// show an ad block in the footer.
// todo: stop selling user info
if( ! View::is('index', 'txt', '404') ): ?>
<div class="box ads-footer">
	<p class="title"><?php _e('Advertising') ?></p>
	<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- Responsive -->
	<ins class="adsbygoogle"
		style="display:block"
		data-ad-client="ca-pub-1967021427191293"
		data-ad-slot="1547888976"
		data-ad-format="auto">
	</ins>
	<script>
		(adsbygoogle = window.adsbygoogle || []).push({});
	</script>
</div>
<?php endif
/** the google analytics **/
?>
<script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){ (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m) })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
ga('create', 'UA-69290712-1', 'auto');
ga('send', 'pageview');
var workerpath = "<?php View::load_script('vendor/recorderWorker.js') ?>";
var lamepath   = "<?php View::load_script('vendor/lame.all.js') ?>";
var ajaxurl    = '<?php echo url() . "ajax/" ?>';
var swfpath    = '<?php echo url() . "assets/swf/" ?>';
<?php if( is_logged() && ! View::is('404') ):
	$current_user = (new \models\User())->get_current_user();
?>
var upload_file_limit = "<?php echo $current_user->get_limit('file_upload') ?>";
var max_duration      = "<?php echo $current_user->get_limit('audio_duration') ?>";
<?php endif ?>
</script>
<?php if( View::is('index', 'txt') ): // index or any text page (terms,about,etc) ?>
<footer class="page-footer grey darken-3">
	<div class="container">
		<div class="row">
			<div class="col l6 s12">
				<h5 class="white-text">
					<?php _e("We've reached the end") ?>
				</h5>
				<p class="grey-text text-lighten-4">
					<?php _e('Have we?') ?>
				</p>
			</div>
			<div class="col l4 offset-l2 s12">
				<h5 class="white-text">
					<?php _e("More info") ?>
				</h5>
				<ul>
					<li>
						<a class="grey-text text-lighten-4" href="<?php echo url('about') ?>">
							<?php _e("About") ?>
						</a>
					</li>
					<li>
						<a class="grey-text text-lighten-4" href="<?php echo url('terms') ?>">
							<?php _e("Terms and conditions") ?>
						</a>
					</li>
					<li>
						<a class="grey-text text-lighten-4" href="<?php echo url('privacy') ?>">
							<?php _e("Privacy Policy") ?>
						</a>
					</li>
					<li>
						<a class="grey-text text-lighten-4" href="<?php echo url('faq') ?>">
							<?php _e("FAQ") ?>
						</a>
					</li>
				</ul>
			</div>
		</div>
		</div>
		  <div class="footer-copyright grey darken-4">
			<div class="container">
			TwitAudio © <?php echo date('Y') ?>
				<div class="right">
					<a
					title="<?php _e('Follow us on Twitter') ?>"
					class="grey-text text-lighten-4" href="//twitter.com/twit_audio">
						<i class="fa fa-twitter"></i>
					</a>&nbsp;
					<a class="grey-text text-lighten-4" href="//fb.com/twitaudio">
						<i class="fa fa-facebook"></i>
					</a>
				</div>
			</div>
		</div>
</footer>
<?php endif ?>
<?php if( is_logged() ): ?>
<div id="settings" class="modal">
	<div class="modal-content">
		<h4><?php _e('Settings') ?></h4>
		<?php View::load_full_template('settings') ?>
	</div>
	<div class="modal-footer">
		<a href="javascript:void(0);" class="modal-action modal-close waves-effect waves-green btn-flat"><?php _e('Close') ?></a>
	</div>
</div>
<?php endif;
	$all_scripts = file_get_contents(
			$_SERVER['DOCUMENT_ROOT'] . '/assets/js/scripts.json'
		);
	$all_scripts = json_decode( $all_scripts, true );
	if( '0' === $GLOBALS['_CONFIG']['minify_html'] ) {
		// if not live
		foreach( $all_scripts as $dir => $scripts ):
			$scripts_length = count($scripts);
			for($i = 0; $i < $scripts_length; $i++):
		?>
				<script
				type="text/javascript"
				src="<?php View::load_script( $dir . '/' . $scripts[$i] ) ?>"
				></script>
		<?php
			endfor;
		endforeach;
	}else{
		// live!
		foreach( $all_scripts as $dir => $scripts ): ?>
		<script
		type="text/javascript"
		src="<?php View::load_script( $dir . '.js' ) ?>"
		></script>
		<?php 
		endforeach;
	}
?>
</body>
</html>