<?php
use \application\View;
?>
<div class="box ads_box">
	<p class="title">Advertising</p>
	<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- Responsive -->
	<ins class="adsbygoogle"
		style="display:block"
		data-ad-client="ca-pub-1967021427191293"
		data-ad-slot="1547888976"
		data-ad-format="auto">
	</ins>
	<script>
		(adsbygoogle = window.adsbygoogle || []).push({});
	</script>
</div>
<div class="box">
	<ul class="links">
		<li>
			<a href="<?php echo url() . 'about' ?>">
				About
			</a>
		</li>
		<li>
			<a href="<?php echo url() . 'terms' ?>">
				Terms
			</a>
		</li>
		<li>
			<a href="<?php echo url() . 'privacy' ?>">
				Privacy
			</a>
		</li>
		<li>
			<a href="<?php echo url() . 'faq' ?>">
				FAQ
			</a>
		</li>
		<li>
			 <a
			 class="dropdown-button"
			 href="javascript:void(0)"
			 data-activates='more'>
			 	More
			 	<b class="caret"></b>
			 </a>
		</li>
	</ul>
	<ul class='dropdown-content more'>
		<li>
			<a target="_blank" href="//twitter.com/twit_audio">
				Our Twitter
			</a>
		</li>
		<li>
			<a target="_blank" href="//fb.com/twitaudio">
				Our Facebook
			</a>
		</li>
	</ul>
</div>