<?php
use \application\Views;
?>
<div class="box ads_box">
	<p class="title"><?php _e('Advertising') ?></p>
	<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- Responsive -->
	<ins class="adsbygoogle"
		style="display:block"
		data-ad-client="ca-pub-1967021427191293"
		data-ad-slot="1547888976"
		data-ad-format="auto">
	</ins>
	<script>
		(adsbygoogle = window.adsbygoogle || []).push({});
	</script>
</div>
<div class="box">
	<ul class="links">
		<li>
			<a href="<?php echo url() . 'about' ?>">
				<?php _e('About') ?>
			</a>
		</li>
		<li>
			<a href="<?php echo url() . 'tos' ?>">
				<?php _e('Terms') ?>
			</a>
		</li>
		<li>
			<a href="<?php echo url() . 'privacy' ?>">
				<?php _e('Privacy') ?>
			</a>
		</li>
		<li>
			<a href="<?php echo url() . 'faq' ?>">
				<?php _e('FAQ') ?>
			</a>
		</li>
		<li>
			 <a
			 class="dropdown-button"
			 href="javascript:void(0)"
			 data-activates='more'>
			 	<?php _e('More') ?>
			 	<b class="caret"></b>
			 </a>
		</li>
	</ul>
	<ul id='more' class='dropdown-content'>
		<li>
			<a target="_blank" href="//twitter.com/twit_audio">
				<?php _e('Our Twitter') ?>
			</a>
		</li>
		<li>
			<a target="_blank" href="//fb.com/twitaudio">
				<?php _e('Our Facebook') ?>
			</a>
		</li>
	</ul>
</div>